import json
import os

notebook_path = "r2ai_kaggle.ipynb"

# Define cells
cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🚀 R2AI 2026 - Legal RAG End-to-End Execution Notebook\n",
            "\n",
            "Notebook này chứa toàn bộ pipeline RAG chạy offline sử dụng mô hình bkai-bi-encoder, PhoRanker và Qwen-0.5B/1.5B/7B.\n",
            "\n",
            "### Hướng dẫn chuẩn bị trước khi chạy:\n",
            "1. **Upload Dataset lên Kaggle:**\n",
            "   - Hãy upload file `database/local_chunks.db`, `database/local_chunks.index` và `R2AIStage1DATA.json` lên Kaggle dưới dạng một Dataset (ví dụ: `r2ai-project-data`).\n",
            "2. **Thêm Dataset vào Notebook:**\n",
            "   - Mở Notebook này trên Kaggle, góc phải chọn **+ Add Input** -> Tìm và chọn dataset `r2ai-project-data` của bạn.\n",
            "3. **Bật GPU:**\n",
            "   - Chọn **Settings** (ở góc phải) -> **Accelerator** -> Chọn **GPU T4** hoặc **GPU T4 x2**."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 📦 Bước 1: Cài đặt các thư viện cần thiết"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "!pip install -q underthesea sentence-transformers faiss-cpu transformers accelerate torch vllm"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 📂 Bước 2: Đồng bộ cơ sở dữ liệu và dữ liệu đầu vào"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import sys\n",
            "import re\n",
            "import io\n",
            "import time\n",
            "import sqlite3\n",
            "import numpy as np\n",
            "from typing import List, Optional, Literal\n",
            "\n",
            "PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))\n",
            "sys.path.insert(0, PROJECT_ROOT)\n",
            "\n",
            "LOCAL_DB_PATH = os.path.join(PROJECT_ROOT, \"database\", \"local_chunks.db\")\n",
            "\n",
            "# \u2500\u2500\u2500 Reuse RetrievalResult t\u1eeb retriever.py \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "from dataclasses import dataclass, field\n",
            "\n",
            "@dataclass\n",
            "class RetrievalResult:\n",
            "    chunk_id: str\n",
            "    document_id: int\n",
            "    chunk_index: int\n",
            "    content: str\n",
            "    doc_number: str\n",
            "    title: str\n",
            "    legal_type: str\n",
            "    score: float\n",
            "    source: str\n",
            "    article_hint: Optional[str] = None\n",
            "    best_chunk_content: Optional[str] = None\n",
            "\n",
            "    def format_relevant_doc(self) -> str:\n",
            "        return f\"{self.doc_number}|{self.legal_type} {self.doc_number} {self.title}\"\n",
            "\n",
            "    def format_relevant_article(self) -> str:\n",
            "        doc_str = self.format_relevant_doc()\n",
            "        article = self.article_hint or \"To\u00e0n b\u1ed9\"\n",
            "        return f\"{doc_str}|{article}\"\n",
            "\n",
            "_ARTICLE_PATTERN = re.compile(\n",
            "    r\"(?:^|\\s)(\u0110i\u1ec1u\\s+\\d+[a-zA-Z]?)\",\n",
            "    re.MULTILINE | re.UNICODE\n",
            ")\n",
            "\n",
            "def extract_article_hint(content: str) -> Optional[str]:\n",
            "    m = _ARTICLE_PATTERN.search(content)\n",
            "    if m:\n",
            "        return m.group(1).strip()\n",
            "    return None\n",
            "\n",
            "\n",
            "\n",
            "# \u2500\u2500\u2500 Parse metadata t\u1eeb chunk content header \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "# Format: \"V\u0103n b\u1ea3n: Ngh\u1ecb \u0111\u1ecbnh 39/2018/N\u0110-CP v\u1ec1 h\u01b0\u1edbng d\u1eabn ... (39/2018/N\u0110-CP)\"\n",
            "_CONTENT_HEADER_RE = re.compile(\n",
            "    r'V\\u0103n b\\u1ea3n:\\s*(.+?)\\s*\\(([^)]+)\\)',\n",
            "    re.MULTILINE | re.UNICODE | re.DOTALL\n",
            ")\n",
            "\n",
            "def _parse_meta_from_content(content: str) -> dict:\n",
            "    \"\"\"Parse document metadata t\u1eeb d\u00f2ng header trong chunk content.\"\"\"\n",
            "    m = _CONTENT_HEADER_RE.search(content[:400])\n",
            "    if not m:\n",
            "        return {\"document_number\": \"\", \"title\": \"\", \"legal_type\": \"\"}\n",
            "\n",
            "    full_title = m.group(1).strip()\n",
            "    full_title = re.sub(r'\\s+', ' ', full_title)\n",
            "    doc_number = m.group(2).strip()\n",
            "\n",
            "    # T\u00e1ch legal_type (lo\u1ea1i v\u0103n b\u1ea3n)\n",
            "    legal_type_match = re.match(\n",
            "        r'^(Lu\\u1eadt|B\\u1ed9 lu\\u1eadt|Ngh\\u1ecb \\u0111\\u1ecbnh|Th\\u00f4ng t\\u01b0|'\n",
            "        r'Quy\\u1ebft \\u0111\\u1ecbnh|Ngh\\u1ecb quy\\u1ebft|Ph\\u00e1p l\\u1ec7nh|'\n",
            "        r'C\\u00f4ng v\\u0103n|Th\\u00f4ng b\\u00e1o|Ch\\u1ec9 th\\u1ecb)\\b',\n",
            "        full_title, re.UNICODE\n",
            "    )\n",
            "    legal_type = legal_type_match.group(1) if legal_type_match else \"\"\n",
            "\n",
            "    # Title = x\u00f3a \"<legal_type> <doc_number>\" \u1edf \u0111\u1ea7u\n",
            "    title = full_title\n",
            "    if legal_type and doc_number:\n",
            "        title = re.sub(\n",
            "            rf'^{re.escape(legal_type)}\\s+{re.escape(doc_number)}\\s*',\n",
            "            '', title\n",
            "        ).strip()\n",
            "\n",
            "    return {\n",
            "        \"document_number\": doc_number,\n",
            "        \"title\": title,\n",
            "        \"legal_type\": legal_type,\n",
            "    }\n",
            "\n",
            "\n",
            "def _tokenize(text: str) -> List[str]:\n",
            "    \"\"\"Tokenize \u0111\u01a1n gi\u1ea3n cho fallback search.\"\"\"\n",
            "    tokens = re.split(r'[\\s\\.,;:!\\?\\\"\\'()\\[\\]{}\\-/\\\\]+', text.lower())\n",
            "    return [t for t in tokens if len(t) >= 2]\n",
            "\n",
            "PROJECT_ROOT = \"/kaggle/working\"\n",
            "LOCAL_DB_PATH = os.path.join(PROJECT_ROOT, \"database\", \"local_chunks.db\")\n",
            "\n",
            "class LocalRetriever:\n",
            "    \"\"\"\n",
            "    Retriever ho\u00e0n to\u00e0n local, kh\u00f4ng c\u1ea7n internet.\n",
            "\n",
            "    Args:\n",
            "        db_path      : \u0111\u01b0\u1eddng d\u1eabn SQLite\n",
            "        top_k        : s\u1ed1 k\u1ebft qu\u1ea3\n",
            "        vector_weight: tr\u1ecdng s\u1ed1 vector trong RRF hybrid\n",
            "        fts_weight   : tr\u1ecdng s\u1ed1 FTS trong RRF hybrid\n",
            "        rrf_k        : h\u1eb1ng s\u1ed1 RRF\n",
            "    \"\"\"\n",
            "\n",
            "    def __init__(\n",
            "        self,\n",
            "        db_path: str = LOCAL_DB_PATH,\n",
            "        top_k: int = 10,\n",
            "        vector_weight: float = 0.3,\n",
            "        fts_weight: float = 0.7,\n",
            "        rrf_k: int = 60,\n",
            "    ):\n",
            "        self.db_path = db_path\n",
            "        self.top_k = top_k\n",
            "        self.vector_weight = vector_weight\n",
            "        self.fts_weight = fts_weight\n",
            "        self.rrf_k = rrf_k\n",
            "        self._conn: Optional[sqlite3.Connection] = None\n",
            "        self._model = None\n",
            "        self._reranker = None\n",
            "\n",
            "    # \u2500\u2500 K\u1ebft n\u1ed1i \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "    def _get_conn(self) -> sqlite3.Connection:\n",
            "        if self._conn is None:\n",
            "            if not os.path.exists(self.db_path):\n",
            "                raise FileNotFoundError(f\"SQLite DB not found: {self.db_path}\")\n",
            "            self._conn = sqlite3.connect(self.db_path, check_same_thread=False)\n",
            "            self._conn.row_factory = sqlite3.Row\n",
            "            \n",
            "            # SQLite performance tuning\n",
            "            try:\n",
            "                cur = self._conn.cursor()\n",
            "                cur.execute(\"PRAGMA journal_mode=WAL;\")\n",
            "                cur.execute(\"PRAGMA synchronous=OFF;\")\n",
            "                cur.execute(\"PRAGMA cache_size=-2000000;\") # 2GB cache\n",
            "                cur.execute(\"PRAGMA temp_store=MEMORY;\")\n",
            "                cur.execute(\"PRAGMA mmap_size=3000000000;\") # 3GB memory map\n",
            "            except Exception as e:\n",
            "                print(f\"[local] Warning: Failed to apply SQLite PRAGMAs: {e}\")\n",
            "        return self._conn\n",
            "\n",
            "    def close(self):\n",
            "        if self._conn:\n",
            "            self._conn.close()\n",
            "            self._conn = None\n",
            "\n",
            "    # \u2500\u2500 Embedding model \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "    def _get_model(self):\n",
            "        if self._model is None:\n",
            "            import os\n",
            "            from sentence_transformers import SentenceTransformer\n",
            "            import torch\n",
            "            device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
            "            print(f\"[local] Loading BAAI/bge-m3 on device '{device}'...\", flush=True)\n",
            "            t0 = time.time()\n",
            "            self._model = SentenceTransformer(\n",
            "                \"BAAI/bge-m3\", device=device\n",
            "            )\n",
            "            print(f\"[local] Model loaded in {time.time()-t0:.1f}s\", flush=True)\n",
            "        return self._model\n",
            "\n",
            "    def embed_query(self, query: str) -> np.ndarray:\n",
            "        model = self._get_model()\n",
            "        vec = model.encode([query], show_progress_bar=False)[0]\n",
            "        return vec.astype(np.float32)\n",
            "\n",
            "    # \u2500\u2500 FTS5 check \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "    def _has_fts5_index(self) -> bool:\n",
            "        conn = self._get_conn()\n",
            "        cur = conn.cursor()\n",
            "        cur.execute(\n",
            "            \"SELECT name FROM sqlite_master WHERE type='table' AND name='chunks_fts5';\"\n",
            "        )\n",
            "        result = cur.fetchone()\n",
            "        if result is None:\n",
            "            return False\n",
            "        # Verify schema is correct (no content_rowid='id' bug)\n",
            "        cur.execute(\"SELECT sql FROM sqlite_master WHERE name='chunks_fts5';\")\n",
            "        sql = cur.fetchone()\n",
            "        if sql:\n",
            "            fts_sql = sql[0] or \"\"\n",
            "            # Bad schema: content_rowid='id' where id is TEXT\n",
            "            if \"content_rowid='id'\" in fts_sql:\n",
            "                return False\n",
            "        return True\n",
            "\n",
            "    # \u2500\u2500 FTS Search \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "    def fts_search(self, query: str, top_k: Optional[int] = None) -> List[RetrievalResult]:\n",
            "        \"\"\"\n",
            "        FTS search v\u1edbi SQLite FTS5 BM25 native.\n",
            "        S\u1eed d\u1ee5ng c\u1ea5u tr\u00fac AND/OR th\u00f4ng minh d\u1ef1a tr\u00ean ph\u00e2n t\u00edch ng\u1eef ngh\u0129a \u0111\u1ec3 tr\u00e1nh g\u00e2y nhi\u1ec5u.\n",
            "        Fallback sang LIKE search n\u1ebfu FTS5 index ch\u01b0a \u0111\u01b0\u1ee3c t\u1ea1o \u0111\u00fang.\n",
            "        \"\"\"\n",
            "        k = top_k or self.top_k\n",
            "        \n",
            "        conn = self._get_conn()\n",
            "        cur = conn.cursor()\n",
            "\n",
            "        # Helper function to execute two-step FTS search to avoid SQLite slow JOIN behavior\n",
            "        def _execute_fts_query(match_expr: str, limit: int) -> List[RetrievalResult]:\n",
            "            try:\n",
            "                cur.execute(\"\"\"\n",
            "                    SELECT rowid, -bm25(chunks_fts5) AS score\n",
            "                    FROM chunks_fts5\n",
            "                    WHERE chunks_fts5 MATCH ?\n",
            "                    ORDER BY bm25(chunks_fts5)\n",
            "                    LIMIT ?;\n",
            "                \"\"\", (match_expr, limit))\n",
            "                rows = cur.fetchall()\n",
            "                if not rows:\n",
            "                    return []\n",
            "                    \n",
            "                rowids = [r[0] for r in rows]\n",
            "                scores = {r[0]: float(r[1]) if r[1] is not None else 0.0 for r in rows}\n",
            "                \n",
            "                placeholders = \",\".join(\"?\" for _ in rowids)\n",
            "                cur.execute(f\"\"\"\n",
            "                    SELECT rowid, id, document_id, chunk_index, content\n",
            "                    FROM document_chunks\n",
            "                    WHERE rowid IN ({placeholders})\n",
            "                \"\"\", rowids)\n",
            "                details = cur.fetchall()\n",
            "                \n",
            "                results_list = []\n",
            "                for row in details:\n",
            "                    r_id, cid, doc_id, chunk_idx, content = row\n",
            "                    score = scores.get(r_id, 0.0)\n",
            "                    meta = _parse_meta_from_content(content or \"\")\n",
            "                    results_list.append(RetrievalResult(\n",
            "                        chunk_id=str(cid),\n",
            "                        document_id=doc_id,\n",
            "                        chunk_index=chunk_idx,\n",
            "                        content=content or \"\",\n",
            "                        doc_number=meta[\"document_number\"],\n",
            "                        title=meta[\"title\"],\n",
            "                        legal_type=meta[\"legal_type\"],\n",
            "                        score=score,\n",
            "                        source=\"fts\",\n",
            "                        article_hint=extract_article_hint(content or \"\"),\n",
            "                    ))\n",
            "                results_list.sort(key=lambda x: x.score, reverse=True)\n",
            "                return results_list\n",
            "            except Exception as e:\n",
            "                print(f\"[local][FTS5] MATCH query error: {e}\")\n",
            "                return []\n",
            "\n",
            "        if self._has_fts5_index():\n",
            "            # X\u00e2y d\u1ef1ng c\u00e2u truy v\u1ea5n FTS c\u1ea5u tr\u00fac AND/OR\n",
            "            q_lower = query.lower()\n",
            "            \n",
            "            # Ph\u00e2n nh\u00f3m th\u1ef1c th\u1ec3 (Subjects) v\u00e0 Ch\u1ee7 \u0111\u1ec1/H\u00e0nh \u0111\u1ed9ng (Topics/Actions)\n",
            "            subjects = {\n",
            "                \"incubator_coworking\": {\n",
            "                    \"keywords\": [\"\u01b0\u01a1m t\u1ea1o\", \"l\u00e0m vi\u1ec7c chung\"],\n",
            "                    \"syns\": ['\"\u01b0\u01a1m t\u1ea1o\"', '\"c\u01a1 s\u1edf \u01b0\u01a1m t\u1ea1o\"', '\"khu l\u00e0m vi\u1ec7c chung\"', '\"l\u00e0m vi\u1ec7c chung\"']\n",
            "                },\n",
            "                \"sme\": {\n",
            "                    \"keywords\": [\"doanh nghi\u1ec7p nh\u1ecf v\u00e0 v\u1eeba\", \"nh\u1ecf v\u00e0 v\u1eeba\", \"sme\", \"si\u00eau nh\u1ecf\"],\n",
            "                    \"syns\": ['\"doanh nghi\u1ec7p nh\u1ecf v\u00e0 v\u1eeba\"', '\"nh\u1ecf v\u00e0 v\u1eeba\"', '\"doanh nghi\u1ec7p nh\u1ecf\"', '\"doanh nghi\u1ec7p si\u00eau nh\u1ecf\"']\n",
            "                },\n",
            "                \"labor\": {\n",
            "                    \"keywords\": [\"nh\u00e2n vi\u00ean\", \"lao \u0111\u1ed9ng\", \"ng\u01b0\u1eddi lao \u0111\u1ed9ng\", \"th\u1eed vi\u1ec7c\", \"k\u00fd h\u1ee3p \u0111\u1ed3ng\", \"sa th\u1ea3i\", \"\u0111u\u1ed5i vi\u1ec7c\", \"ngh\u1ec9 vi\u1ec7c\", \"l\u01b0\u01a1ng\"],\n",
            "                    \"syns\": ['\"ng\u01b0\u1eddi lao \u0111\u1ed9ng\"', '\"lao \u0111\u1ed9ng\"', '\"nh\u00e2n vi\u00ean\"', '\"h\u1ee3p \u0111\u1ed3ng lao \u0111\u1ed9ng\"']\n",
            "                }\n",
            "            }\n",
            "            \n",
            "            topics = {\n",
            "                \"tax_land\": {\n",
            "                    \"keywords\": [\"thu\u1ebf\", \"\u0111\u1ea5t \u0111ai\", \"m\u1eb7t b\u1eb1ng\", \"ti\u1ec1n thu\u00ea\"],\n",
            "                    \"syns\": ['\"thu\u1ebf\"', '\"\u0111\u1ea5t \u0111ai\"', '\"m\u1eb7t b\u1eb1ng\"', '\"thu\u00ea \u0111\u1ea5t\"', '\"\u01b0u \u0111\u00e3i thu\u1ebf\"', '\"ti\u1ec1n s\u1eed d\u1ee5ng \u0111\u1ea5t\"']\n",
            "                },\n",
            "                \"bidding\": {\n",
            "                    \"keywords\": [\"\u0111\u1ea5u th\u1ea7u\", \"nh\u00e0 th\u1ea7u\", \"g\u00f3i th\u1ea7u\"],\n",
            "                    \"syns\": ['\"\u0111\u1ea5u th\u1ea7u\"', '\"nh\u00e0 th\u1ea7u\"', '\"l\u1ef1a ch\u1ecdn nh\u00e0 th\u1ea7u\"', '\"g\u00f3i th\u1ea7u\"', '\"x\u1ebfp h\u1ea1ng h\u1ed3 s\u01a1\"']\n",
            "                },\n",
            "                \"degrees_holding\": {\n",
            "                    \"keywords\": [\"gi\u1eef\", \"b\u1eb1ng\", \"v\u0103n b\u1eb1ng\", \"ch\u1ee9ng ch\u1ec9\", \"gi\u1ea5y t\u1edd\", \"b\u1eb1ng c\u1ea5p\"],\n",
            "                    \"syns\": ['\"gi\u1eef\"', '\"thu gi\u1eef\"', '\"t\u1ea1m gi\u1eef\"', '\"v\u0103n b\u1eb1ng\"', '\"ch\u1ee9ng ch\u1ec9\"', '\"gi\u1ea5y t\u1edd t\u00f9y th\u00e2n\"', '\"b\u1ea3n ch\u00ednh\"', '\"b\u1eb1ng c\u1ea5p\"']\n",
            "                }\n",
            "            }\n",
            "\n",
            "            active_subjects = []\n",
            "            for s_name, s_info in subjects.items():\n",
            "                if any(kw in q_lower for kw in s_info[\"keywords\"]):\n",
            "                    active_subjects.append(s_info[\"syns\"])\n",
            "                    \n",
            "            active_topics = []\n",
            "            for t_name, t_info in topics.items():\n",
            "                if any(kw in q_lower for kw in t_info[\"keywords\"]):\n",
            "                    active_topics.append(t_info[\"syns\"])\n",
            "                    \n",
            "            clauses = []\n",
            "            if active_subjects:\n",
            "                flat_subjects = []\n",
            "                for s in active_subjects:\n",
            "                    flat_subjects.extend(s)\n",
            "                flat_subjects = list(dict.fromkeys(flat_subjects))\n",
            "                clauses.append(\"(\" + \" OR \".join(flat_subjects) + \")\")\n",
            "                \n",
            "            if active_topics:\n",
            "                flat_topics = []\n",
            "                for t in active_topics:\n",
            "                    flat_topics.extend(t)\n",
            "                flat_topics = list(dict.fromkeys(flat_topics))\n",
            "                clauses.append(\"(\" + \" OR \".join(flat_topics) + \")\")\n",
            "\n",
            "            fts_expr = \"\"\n",
            "            if clauses:\n",
            "                fts_expr = \" AND \".join(clauses)\n",
            "                print(f\"[local][FTS5] Structured query: {fts_expr}\")\n",
            "                results = _execute_fts_query(fts_expr, k)\n",
            "                if results:\n",
            "                    return results\n",
            "                print(f\"[local][FTS5] Structured query returned 0 results. Trying fallback OR...\")\n",
            "\n",
            "            # Fallback sang OR \u0111\u01a1n gi\u1ea3n c\u1ee7a c\u00e1c t\u1eeb kh\u00f3a c\u00f3 ngh\u0129a (lo\u1ea1i b\u1ecf stopword)\n",
            "            GRAMMAR_STOPWORDS = {\n",
            "                \"v\u00e0\", \"ho\u1eb7c\", \"nh\u01b0ng\", \"v\u00ec\", \"n\u00ean\", \"c\u1ee7a\", \"c\u00e1c\", \"nh\u1eefng\", \"l\u00e0\", \"c\u00f3\", \n",
            "                \"trong\", \"t\u1ea1i\", \"\u0111\u1ec3\", \"theo\", \"\u0111\u01b0\u1ee3c\", \"b\u1ecb\", \"cho\", \"ra\", \"v\u00e0o\", \"l\u00ean\", \n",
            "                \"xu\u1ed1ng\", \"do\", \"t\u1eeb\", \"\u0111\u1ebfn\", \"b\u1eb1ng\", \"with\", \"v\u1edbi\", \"v\u1ec1\", \"nh\u01b0\", \"th\u00ec\", \n",
            "                \"m\u00e0\", \"khi\", \"g\u00ec\", \"n\u00e0y\", \"\u0111\u00f3\", \"kia\", \"n\u1ecd\", \"th\u1ebf\", \"v\u1eady\", \"n\u00e0o\", \"ai\", \n",
            "                \"\u0111\u00e2u\", \"c\u00e1i\", \"con\", \"chi\u1ebfc\", \"n\u1ebfu\", \"s\u1ebd\", \"ph\u1ea3i\", \"sao\", \"th\u1ebf\"\n",
            "            }\n",
            "            words = [w.lower().strip() for w in query.split()]\n",
            "            terms = []\n",
            "            for w in words:\n",
            "                w = re.sub(r'[^\\w\\s\\u00C0-\\u024F\\u1E00-\\u1EFF]', '', w).strip()\n",
            "                if w and len(w) >= 3 and w not in GRAMMAR_STOPWORDS:\n",
            "                    terms.append(f'\"{w}\"')\n",
            "            \n",
            "            if terms:\n",
            "                fallback_expr = \" OR \".join(terms)\n",
            "                print(f\"[local][FTS5] Fallback OR query: {fallback_expr}\")\n",
            "                results = _execute_fts_query(fallback_expr, k)\n",
            "                if results:\n",
            "                    return results\n",
            "\n",
            "            print(\"[local][FTS5] 0 results from FTS5. Trying LIKE fallback...\")\n",
            "\n",
            "        # LIKE fallback search (slower, for queries without diacritics)\n",
            "        print(\"[local][FTS] Using LIKE fallback search...\")\n",
            "        keywords = [w for w in query.split() if len(w) >= 3][:5]\n",
            "        if not keywords:\n",
            "            return []\n",
            "\n",
            "        like_pattern = f\"%{keywords[0]}%\"\n",
            "        cur.execute(\"\"\"\n",
            "            SELECT id, document_id, chunk_index, content\n",
            "            FROM document_chunks\n",
            "            WHERE content LIKE ?\n",
            "            LIMIT ?;\n",
            "        \"\"\", (like_pattern, k * 3))\n",
            "        rows = cur.fetchall()\n",
            "\n",
            "        results = []\n",
            "        for row in rows:\n",
            "            cid, doc_id, chunk_idx, content = row[0], row[1], row[2], row[3] or \"\"\n",
            "            score = float(sum(1 for kw in keywords if kw in content))\n",
            "            if score == 0:\n",
            "                continue\n",
            "            meta = _parse_meta_from_content(content)\n",
            "            results.append(RetrievalResult(\n",
            "                chunk_id=str(cid),\n",
            "                document_id=doc_id,\n",
            "                chunk_index=chunk_idx,\n",
            "                content=content,\n",
            "                doc_number=meta[\"document_number\"],\n",
            "                title=meta[\"title\"],\n",
            "                legal_type=meta[\"legal_type\"],\n",
            "                score=score,\n",
            "                source=\"fts\",\n",
            "                article_hint=extract_article_hint(content),\n",
            "            ))\n",
            "        results.sort(key=lambda x: -x.score)\n",
            "        return results[:k]\n",
            "\n",
            "    # \u2500\u2500 FAISS Vector Search \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "    def _get_faiss_index(self):\n",
            "        \"\"\"L\u1ea5y ho\u1eb7c t\u1ef1 \u0111\u1ed9ng build FAISS index t\u1eeb SQLite database.\"\"\"\n",
            "        import faiss\n",
            "        index_path = os.path.join(os.path.dirname(self.db_path), \"local_chunks.index\")\n",
            "        \n",
            "        if not hasattr(self, \"_faiss_index\") or self._faiss_index is None:\n",
            "            if os.path.exists(index_path):\n",
            "                print(f\"[local] Loading FAISS index from {index_path}...\", flush=True)\n",
            "                t0 = time.time()\n",
            "                self._faiss_index = faiss.read_index(index_path)\n",
            "                print(f\"[local] FAISS index loaded in {time.time()-t0:.2f}s\", flush=True)\n",
            "            else:\n",
            "                print(f\"[local] FAISS index not found. Building FAISS index from {self.db_path} (one-time setup)...\", flush=True)\n",
            "                t0 = time.time()\n",
            "                conn = self._get_conn()\n",
            "                cur = conn.cursor()\n",
            "                cur.execute(\"SELECT rowid, embedding FROM document_chunks WHERE embedding IS NOT NULL;\")\n",
            "                rowids = []\n",
            "                embeddings = []\n",
            "                for rowid, emb_bytes in cur:\n",
            "                    if not emb_bytes:\n",
            "                        continue\n",
            "                    emb = np.frombuffer(emb_bytes, dtype=np.float32)\n",
            "                    rowids.append(rowid)\n",
            "                    embeddings.append(emb)\n",
            "                \n",
            "                if not embeddings:\n",
            "                    raise ValueError(\"No embeddings found in database to build FAISS index!\")\n",
            "                \n",
            "                embeddings = np.array(embeddings, dtype=np.float32)\n",
            "                rowids = np.array(rowids, dtype=np.int64)\n",
            "                \n",
            "                # Chu\u1ea9n h\u00f3a vector L2 \u0111\u1ec3 t\u00ecm ki\u1ebfm Cosine Similarity b\u1eb1ng Inner Product\n",
            "                norms = np.linalg.norm(embeddings, axis=1, keepdims=True)\n",
            "                norms[norms == 0] = 1.0\n",
            "                embeddings = embeddings / norms\n",
            "                \n",
            "                dim = embeddings.shape[1]\n",
            "                quantizer = faiss.IndexFlatIP(dim)\n",
            "                index = faiss.IndexIDMap(quantizer)\n",
            "                index.add_with_ids(embeddings, rowids)\n",
            "                \n",
            "                # L\u01b0u index \u0111\u1ec3 c\u00e1c l\u1ea7n sau d\u00f9ng ngay\n",
            "                faiss.write_index(index, index_path)\n",
            "                self._faiss_index = index\n",
            "                print(f\"[local] FAISS index built and saved in {time.time()-t0:.2f}s\", flush=True)\n",
            "                \n",
            "        return self._faiss_index\n",
            "\n",
            "    def vector_search(self, query: str, top_k: Optional[int] = None) -> List[RetrievalResult]:\n",
            "        \"\"\"T\u00ecm ki\u1ebfm t\u01b0\u01a1ng \u0111\u1ed3ng vector b\u1eb1ng FAISS index (t\u1ea3i v\u00e0 t\u00ecm c\u1ef1c nhanh).\"\"\"\n",
            "        k = top_k or self.top_k\n",
            "        \n",
            "        query_vec = self.embed_query(query)\n",
            "        query_norm = np.linalg.norm(query_vec)\n",
            "        if query_norm == 0:\n",
            "            return []\n",
            "            \n",
            "        # Chu\u1ea9n h\u00f3a query vector v\u00e0 \u0111\u1ecbnh d\u1ea1ng cho FAISS\n",
            "        query_vec = query_vec / query_norm\n",
            "        query_vec = np.ascontiguousarray(query_vec.reshape(1, -1), dtype=np.float32)\n",
            "        \n",
            "        index = self._get_faiss_index()\n",
            "        scores, indices = index.search(query_vec, k)\n",
            "        scores = scores[0]\n",
            "        indices = indices[0]\n",
            "        \n",
            "        valid_indices = [int(idx) for idx in indices if idx != -1]\n",
            "        if not valid_indices:\n",
            "            return []\n",
            "            \n",
            "        # Truy v\u1ea5n SQLite \u0111\u1ec3 l\u1ea5y th\u00f4ng tin c\u00e1c chunks t\u01b0\u01a1ng \u1ee9ng v\u1edbi rowid\n",
            "        conn = self._get_conn()\n",
            "        cur = conn.cursor()\n",
            "        placeholders = \",\".join(\"?\" for _ in valid_indices)\n",
            "        cur.execute(f\"\"\"\n",
            "            SELECT rowid, id, document_id, chunk_index, content\n",
            "            FROM document_chunks\n",
            "            WHERE rowid IN ({placeholders});\n",
            "        \"\"\", valid_indices)\n",
            "        \n",
            "        rows = cur.fetchall()\n",
            "        row_map = {row[\"rowid\"]: row for row in rows}\n",
            "        \n",
            "        results = []\n",
            "        for idx, score in zip(indices, scores):\n",
            "            idx = int(idx)\n",
            "            if idx not in row_map:\n",
            "                continue\n",
            "            row = row_map[idx]\n",
            "            cid = row[\"id\"]\n",
            "            doc_id = row[\"document_id\"]\n",
            "            chunk_idx = row[\"chunk_index\"]\n",
            "            content = row[\"content\"] or \"\"\n",
            "            \n",
            "            meta = _parse_meta_from_content(content)\n",
            "            results.append(RetrievalResult(\n",
            "                chunk_id=str(cid),\n",
            "                document_id=doc_id,\n",
            "                chunk_index=chunk_idx,\n",
            "                content=content,\n",
            "                doc_number=meta[\"document_number\"],\n",
            "                title=meta[\"title\"],\n",
            "                legal_type=meta[\"legal_type\"],\n",
            "                score=float(score),\n",
            "                source=\"vector\",\n",
            "                article_hint=extract_article_hint(content),\n",
            "            ))\n",
            "        return results\n",
            "\n",
            "    # \u2500\u2500 Hybrid (RRF) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "    def hybrid_search(self, query: str, top_k: Optional[int] = None) -> List[RetrievalResult]:\n",
            "        \"\"\"K\u1ebft h\u1ee3p FTS + vector b\u1eb1ng Reciprocal Rank Fusion.\"\"\"\n",
            "        k = top_k or self.top_k\n",
            "        fetch_k = k * 3\n",
            "\n",
            "        fts_results    = self.fts_search(query,    top_k=fetch_k)\n",
            "        vector_results = self.vector_search(query, top_k=fetch_k)\n",
            "\n",
            "        chunk_map: dict = {}\n",
            "        rrf_scores: dict = {}\n",
            "\n",
            "        def add_ranked(results: List[RetrievalResult], weight: float):\n",
            "            for rank, r in enumerate(results, start=1):\n",
            "                cid = r.chunk_id\n",
            "                if cid not in chunk_map:\n",
            "                    chunk_map[cid] = r\n",
            "                    rrf_scores[cid] = 0.0\n",
            "                rrf_scores[cid] += weight / (rank + self.rrf_k)\n",
            "\n",
            "        add_ranked(fts_results,    self.fts_weight)\n",
            "        add_ranked(vector_results, self.vector_weight)\n",
            "\n",
            "        sorted_ids = sorted(rrf_scores, key=rrf_scores.get, reverse=True)\n",
            "        results = []\n",
            "        for cid in sorted_ids[:k]:\n",
            "            r = chunk_map[cid]\n",
            "            results.append(RetrievalResult(\n",
            "                chunk_id=r.chunk_id,\n",
            "                document_id=r.document_id,\n",
            "                chunk_index=r.chunk_index,\n",
            "                content=r.content,\n",
            "                doc_number=r.doc_number,\n",
            "                title=r.title,\n",
            "                legal_type=r.legal_type,\n",
            "                score=rrf_scores[cid],\n",
            "                source=\"hybrid\",\n",
            "                article_hint=r.article_hint,\n",
            "            ))\n",
            "        return results\n",
            "\n",
            "    def rerank(self, query: str, results: List[RetrievalResult], top_k: Optional[int] = None) -> List[RetrievalResult]:\n",
            "        if not results:\n",
            "            return []\n",
            "            \n",
            "        if self._reranker is None:\n",
            "            import torch\n",
            "            from sentence_transformers import CrossEncoder\n",
            "            device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
            "            print(f\"[local] Loading reranker model BAAI/bge-reranker-v2-m3 on device '{device}'...\", flush=True)\n",
            "            t0 = time.time()\n",
            "            self._reranker = CrossEncoder(\"BAAI/bge-reranker-v2-m3\", device=device)\n",
            "            # Optimize memory if using CUDA\n",
            "            if device == \"cuda\" and hasattr(self._reranker.model, \"half\"):\n",
            "                self._reranker.model.half()\n",
            "            print(f\"[local] Reranker model loaded in {time.time()-t0:.1f}s\", flush=True)\n",
            "            \n",
            "        pairs = []\n",
            "        for r in results:\n",
            "            best_text = getattr(r, 'best_chunk_content', None) or r.content\n",
            "            \n",
            "            # Th\u00eam metadata boosting \u0111\u1ec3 t\u0103ng \u0111\u1ed9 ch\u00ednh x\u00e1c (r\u1ea5t hi\u1ec7u qu\u1ea3 v\u1edbi v\u0103n b\u1ea3n ph\u00e1p lu\u1eadt)\n",
            "            article_str = f\"\u0110i\u1ec1u: {r.article_hint}\\n\" if r.article_hint else \"\"\n",
            "            doc_text = f\"V\u0103n b\u1ea3n: {r.legal_type} {r.doc_number} - {r.title}\\n{article_str}N\u1ed9i dung:\\n{best_text}\"\n",
            "            \n",
            "            pairs.append([query, doc_text])\n",
            "            \n",
            "        t_rerank = time.time()\n",
            "        scores = self._reranker.predict(pairs, show_progress_bar=False)\n",
            "        print(f\"[local] Reranking took {time.time() - t_rerank:.2f}s for {len(pairs)} pairs.\")\n",
            "        \n",
            "        LEGAL_WEIGHT = {\n",
            "            \"Lu\u1eadt\": 1.0,\n",
            "            \"B\u1ed9 lu\u1eadt\": 1.0,\n",
            "            \"Ngh\u1ecb quy\u1ebft\": 0.95,\n",
            "            \"Ngh\u1ecb \u0111\u1ecbnh\": 0.85,\n",
            "            \"Th\u00f4ng t\u01b0\": 0.75,\n",
            "        }\n",
            "        \n",
            "        for r, score in zip(results, scores):\n",
            "            rerank_score = float(score)\n",
            "            # Normalize PhoRanker output to positive if it outputs logits\n",
            "            if rerank_score < 0 or rerank_score > 1.0:\n",
            "                import math\n",
            "                rerank_score = 1 / (1 + math.exp(-max(min(rerank_score, 100), -100)))\n",
            "                \n",
            "            weight = LEGAL_WEIGHT.get(r.legal_type, 0.7)\n",
            "            final_score = rerank_score * weight\n",
            "            \n",
            "            r.score = final_score\n",
            "            r.source = f\"rerank({r.source})\"\n",
            "            \n",
            "        results.sort(key=lambda x: x.score, reverse=True)\n",
            "        \n",
            "        # L\u1ecdc MMR Diversity: max 2 chunk m\u1ed7i document\n",
            "        filtered_results = []\n",
            "        doc_count = {}\n",
            "        for r in results:\n",
            "            doc_id = r.document_id\n",
            "            if doc_count.get(doc_id, 0) < 2:\n",
            "                filtered_results.append(r)\n",
            "                doc_count[doc_id] = doc_count.get(doc_id, 0) + 1\n",
            "        \n",
            "        if top_k:\n",
            "            return filtered_results[:top_k]\n",
            "        return filtered_results\n",
            "\n",
            "    def are_chunks_duplicate(self, c1: RetrievalResult, c2: RetrievalResult) -> bool:\n",
            "        \"\"\"Ki\u1ec3m tra xem hai chunk c\u00f3 tr\u00f9ng l\u1eb7p n\u1ed9i dung \u0111\u00e1ng k\u1ec3 hay kh\u00f4ng.\"\"\"\n",
            "        if c1.document_id == c2.document_id and c1.chunk_index == c2.chunk_index:\n",
            "            return True\n",
            "            \n",
            "        # Tr\u00edch xu\u1ea5t ph\u1ea7n n\u1ed9i dung th\u1ef1c t\u1ebf \u0111\u1ec3 so s\u00e1nh\n",
            "        body1 = c1.content.split(\"| N\u1ed9i dung:\")[-1].strip()\n",
            "        body2 = c2.content.split(\"| N\u1ed9i dung:\")[-1].strip()\n",
            "        \n",
            "        def normalize(text):\n",
            "            text = text.lower()\n",
            "            text = re.sub(r'[^\\w\\s]', '', text)\n",
            "            return set(text.split())\n",
            "            \n",
            "        words1 = normalize(body1)\n",
            "        words2 = normalize(body2)\n",
            "        if not words1 or not words2:\n",
            "            return False\n",
            "            \n",
            "        intersection = words1.intersection(words2)\n",
            "        union = words1.union(words2)\n",
            "        jaccard = len(intersection) / len(union)\n",
            "        \n",
            "        # Jaccard score cao => tr\u00f9ng l\u1eb7p\n",
            "        if jaccard > 0.8:\n",
            "            return True\n",
            "            \n",
            "        # N\u1ebfu tr\u00f9ng \u0110i\u1ec1u/Kho\u1ea3n lu\u1eadt v\u00e0 \u0111\u1ed9 t\u01b0\u01a1ng \u0111\u1ed3ng t\u01b0\u01a1ng \u0111\u1ed1i cao => tr\u00f9ng l\u1eb7p (v\u00ed d\u1ee5 gi\u1eefa Lu\u1eadt v\u00e0 VBHN)\n",
            "        if c1.article_hint and c2.article_hint and c1.article_hint == c2.article_hint:\n",
            "            if \"\u0111i\u1ec1u\" in c1.article_hint.lower() or \"kho\u1ea3n\" in c1.article_hint.lower():\n",
            "                if jaccard > 0.6:\n",
            "                    return True\n",
            "        return False\n",
            "\n",
            "    # \u2500\u2500 Entry point \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
            "\n",
            "\n",
            "    def expand_query(self, query: str) -> str:\n",
            "        \"\"\"Query Expansion b\u1eb1ng rule-based dictionary.\"\"\"\n",
            "        q_lower = query.lower()\n",
            "        expanded_terms = []\n",
            "        \n",
            "        intents = {\n",
            "            \"h\u1ed7 tr\u1ee3\": [\"\u01b0u \u0111\u00e3i\", \"ch\u00ednh s\u00e1ch h\u1ed7 tr\u1ee3\", \"khuy\u1ebfn kh\u00edch\"],\n",
            "            \"\u01b0u \u0111\u00e3i\": [\"mi\u1ec5n\", \"gi\u1ea3m\", \"h\u1ed7 tr\u1ee3\"],\n",
            "            \"mi\u1ec5n\": [\"gi\u1ea3m\", \"kh\u00f4ng ph\u1ea3i n\u1ed9p\", \"\u01b0u \u0111\u00e3i\"],\n",
            "            \"gi\u1ea3m\": [\"mi\u1ec5n\", \"\u01b0u \u0111\u00e3i thu\u1ebf\"],\n",
            "            \"\u0111\u1ea5t \u0111ai\": [\"ti\u1ec1n thu\u00ea \u0111\u1ea5t\", \"ti\u1ec1n s\u1eed d\u1ee5ng \u0111\u1ea5t\", \"m\u1eb7t b\u1eb1ng\", \"\u0111\u1ea5t\"],\n",
            "            \"thu\u1ebf\": [\"thu\u1ebf thu nh\u1eadp doanh nghi\u1ec7p\", \"thu\u1ebf tndn\", \"mi\u1ec5n thu\u1ebf\", \"gi\u1ea3m thu\u1ebf\"]\n",
            "        }\n",
            "        \n",
            "        for k, v in intents.items():\n",
            "            if k in q_lower:\n",
            "                expanded_terms.extend(v)\n",
            "                \n",
            "        if expanded_terms:\n",
            "            new_terms = [t for t in expanded_terms if t not in q_lower]\n",
            "            if new_terms:\n",
            "                return query + \" \" + \" \".join(new_terms)\n",
            "        return query\n",
            "\n",
            "    def expand_to_parent_article(self, results: list) -> list:\n",
            "        \"\"\"Parent Retrieval: L\u1ea5y to\u00e0n b\u1ed9 n\u1ed9i dung c\u1ee7a \u0110i\u1ec1u lu\u1eadt t\u1eeb c\u00e1c chunk ban \u0111\u1ea7u.\"\"\"\n",
            "        if not results:\n",
            "            return []\n",
            "            \n",
            "        target_articles = {}\n",
            "        hit_indexes = {}\n",
            "        for r in results:\n",
            "            if not r.article_hint:\n",
            "                continue\n",
            "            doc_id = r.document_id\n",
            "            if doc_id not in target_articles:\n",
            "                target_articles[doc_id] = set()\n",
            "            target_articles[doc_id].add(r.article_hint)\n",
            "            \n",
            "            # Ghi nh\u1edb v\u1ecb tr\u00ed chunk_index \u0111\u00e3 hit\n",
            "            key = (doc_id, r.article_hint)\n",
            "            if key not in hit_indexes:\n",
            "                hit_indexes[key] = set()\n",
            "            hit_indexes[key].add(r.chunk_index)\n",
            "            \n",
            "        if not target_articles:\n",
            "            return results\n",
            "            \n",
            "        doc_ids = list(target_articles.keys())\n",
            "        conn = self._get_conn()\n",
            "        cur = conn.cursor()\n",
            "        \n",
            "        placeholders = \",\".join(\"?\" for _ in doc_ids)\n",
            "        cur.execute(f\"\"\"\n",
            "            SELECT document_id, chunk_index, content\n",
            "            FROM document_chunks\n",
            "            WHERE document_id IN ({placeholders})\n",
            "            ORDER BY document_id, chunk_index\n",
            "        \"\"\", doc_ids)\n",
            "        \n",
            "        all_chunks = cur.fetchall()\n",
            "        \n",
            "        doc_chunks = {}\n",
            "        for row in all_chunks:\n",
            "            did = row[\"document_id\"]\n",
            "            if did not in doc_chunks:\n",
            "                doc_chunks[did] = []\n",
            "            doc_chunks[did].append(row)\n",
            "            \n",
            "        expanded_articles = {}\n",
            "        \n",
            "        for did, rows in doc_chunks.items():\n",
            "            current_article = None\n",
            "            for row in rows:\n",
            "                content = row[\"content\"] or \"\"\n",
            "                # Import extract_article_hint dynamically or rely on global\n",
            "                from retriever import extract_article_hint\n",
            "                hint = extract_article_hint(content)\n",
            "                if hint:\n",
            "                    current_article = hint\n",
            "                \n",
            "                if current_article and current_article in target_articles[did]:\n",
            "                    key = (did, current_article)\n",
            "                    \n",
            "                    # Windowing limit: Ch\u1ec9 g\u1ed9p n\u1ebfu chunk n\u1eb1m g\u1ea7n v\u1ecb tr\u00ed hit (+/- 2 chunks)\n",
            "                    # Ch\u1ed1ng ph\u00ecnh to context \u0111\u1ed1i v\u1edbi c\u00e1c \u0110i\u1ec1u omnibus (VD: \"s\u1eeda \u0111\u1ed5i, b\u1ed5 sung m\u1ed9t s\u1ed1 \u0111i\u1ec1u\")\n",
            "                    hits = hit_indexes.get(key, set())\n",
            "                    is_near_hit = False\n",
            "                    for h in hits:\n",
            "                        if abs(h - row[\"chunk_index\"]) <= 2:\n",
            "                            is_near_hit = True\n",
            "                            break\n",
            "                            \n",
            "                    if is_near_hit:\n",
            "                        if key not in expanded_articles:\n",
            "                            expanded_articles[key] = []\n",
            "                        expanded_articles[key].append(content)\n",
            "                    \n",
            "        final_results = []\n",
            "        seen_keys = set()\n",
            "        \n",
            "        for r in results:\n",
            "            if not r.article_hint:\n",
            "                final_results.append(r)\n",
            "                continue\n",
            "                \n",
            "            key = (r.document_id, r.article_hint)\n",
            "            if key in seen_keys:\n",
            "                continue\n",
            "            seen_keys.add(key)\n",
            "            \n",
            "            if key in expanded_articles:\n",
            "                # L\u01b0u l\u1ea1i n\u1ed9i dung c\u1ee7a best chunk (chunk ban \u0111\u1ea7u c\u00f3 \u0111i\u1ec3m cao nh\u1ea5t) \u0111\u1ec3 d\u00f9ng cho Rerank\n",
            "                r.best_chunk_content = r.content\n",
            "                \n",
            "                full_content = \"\\n...\\n\".join(expanded_articles[key])\n",
            "                r.content = full_content\n",
            "                r.source += \"_parent_expanded\"\n",
            "                final_results.append(r)\n",
            "            else:\n",
            "                final_results.append(r)\n",
            "                \n",
            "        return final_results\n",
            "\n",
            "    def retrieve(\n",
            "        self,\n",
            "        query: str,\n",
            "        mode: Literal[\"vector\", \"fts\", \"hybrid\"] = \"fts\",\n",
            "        top_k: Optional[int] = None,\n",
            "        rerank: bool = True,\n",
            "    ) -> List[RetrievalResult]:\n",
            "        t0 = time.time()\n",
            "        k = top_k or self.top_k\n",
            "        \n",
            "        # 1. Query Expansion (Intent Understanding)\n",
            "        expanded_query = self.expand_query(query)\n",
            "        \n",
            "        # 2. Truy xu\u1ea5t danh s\u00e1ch \u1ee9ng vi\u00ean (candidate pool)\n",
            "        if rerank:\n",
            "            fetch_k = 50\n",
            "        else:\n",
            "            fetch_k = max(50, k * 4)\n",
            "        \n",
            "        if mode == \"vector\":\n",
            "            results = self.vector_search(expanded_query, top_k=fetch_k)\n",
            "        elif mode == \"fts\":\n",
            "            results = self.fts_search(expanded_query, top_k=fetch_k)\n",
            "        else:\n",
            "            results = self.hybrid_search(expanded_query, top_k=fetch_k)\n",
            "            \n",
            "        # 3. Ti\u1ebfn h\u00e0nh l\u1ecdc tr\u00f9ng l\u1eb7p tr\u01b0\u1edbc \u0111\u1ec3 lo\u1ea1i b\u1ecf nhi\u1ec5u\n",
            "        unique_results = []\n",
            "        for r in results:\n",
            "            is_dup = False\n",
            "            for ur in unique_results:\n",
            "                if self.are_chunks_duplicate(r, ur):\n",
            "                     is_dup = True\n",
            "                     break\n",
            "            if not is_dup:\n",
            "                unique_results.append(r)\n",
            "                \n",
            "        # 4. Parent Retrieval (Thay th\u1ebf cho aggregate_chunks_into_articles)\n",
            "        article_results = self.expand_to_parent_article(unique_results)\n",
            "\n",
            "        # 5. Rerank v\u00e0 l\u1ecdc\n",
            "        if rerank:\n",
            "            results = self.rerank(query, article_results, top_k=None)\n",
            "        else:\n",
            "            article_results.sort(key=lambda x: x.score, reverse=True)\n",
            "            results = article_results\n",
            "\n",
            "        # 4. \u00c1p d\u1ee5ng Absolute & Relative Score Thresholds (Dynamic Thresholding)\n",
            "        if results:\n",
            "            RERANK_THRESHOLD = 0.15\n",
            "            best_score = results[0].score\n",
            "            \n",
            "            relative_threshold_ratio = 0.5\n",
            "            \n",
            "            # Dynamic gap filtering: N\u1ebfu top 1 v\u01b0\u1ee3t tr\u1ed9i ho\u00e0n to\u00e0n top 2\n",
            "            if len(results) > 1:\n",
            "                score_1 = results[0].score\n",
            "                score_2 = results[1].score\n",
            "                if (score_1 - score_2) > 0.2:\n",
            "                    relative_threshold_ratio = 0.8\n",
            "            \n",
            "            filtered_by_score = []\n",
            "            for r in results:\n",
            "                # Gi\u1eef chunk n\u1ebfu th\u1ecfa m\u00e3n ng\u01b0\u1ee1ng tuy\u1ec7t \u0111\u1ed1i v\u00e0 ng\u01b0\u1ee1ng t\u01b0\u01a1ng \u0111\u1ed1i \u0111\u1ed9ng\n",
            "                if r.score >= RERANK_THRESHOLD and r.score >= best_score * relative_threshold_ratio:\n",
            "                    filtered_by_score.append(r)\n",
            "            results = filtered_by_score\n",
            "\n",
            "        # 5. Article-level Dedup (Gi\u1ea3m context th\u1eeba)\n",
            "        seen_articles = set()\n",
            "        deduped = []\n",
            "        for r in results:\n",
            "            article_id = r.format_relevant_article()\n",
            "            if article_id in seen_articles:\n",
            "                continue\n",
            "            seen_articles.add(article_id)\n",
            "            deduped.append(r)\n",
            "        results = deduped\n",
            "\n",
            "        # 6. Intent-aware (Query-aware) Filter\n",
            "        try:\n",
            "            import underthesea\n",
            "            tags = underthesea.pos_tag(query)\n",
            "            important_terms = [word.lower() for word, tag in tags if tag in ['N', 'Np', 'V', 'A', 'M'] and len(word) > 1]\n",
            "            if not important_terms:\n",
            "                important_terms = [w.lower() for w in query.split() if len(w) > 2]\n",
            "        except Exception:\n",
            "            important_terms = [w.lower() for w in query.split() if len(w) > 2]\n",
            "            \n",
            "        filtered_final = []\n",
            "        for r in results:\n",
            "            content_lower = r.content.lower()\n",
            "            # Chunk ph\u1ea3i ch\u1ee9a \u00edt nh\u1ea5t m\u1ed9t term quan tr\u1ecdng (intent keywords) t\u1eeb c\u00e2u h\u1ecfi\n",
            "            if any(term in content_lower for term in important_terms):\n",
            "                filtered_final.append(r)\n",
            "                \n",
            "        # Fallback n\u1ebfu filter qu\u00e1 ng\u1eb7t ngh\u00e8o drop h\u1ebft t\u1ea5t c\u1ea3 k\u1ebft qu\u1ea3\n",
            "        if not filtered_final and results:\n",
            "            filtered_final = results\n",
            "            \n",
            "        results = filtered_final[:k]\n",
            "            \n",
            "        elapsed = time.time() - t0\n",
            "        print(f\"[local] mode={mode} | rerank={rerank} | {len(results)} results | {elapsed:.2f}s\")\n",
            "        return results\n",
            "\n",
            "    @staticmethod\n",
            "    def aggregate_by_document(results: List[RetrievalResult]) -> dict:\n",
            "        \"\"\"Nh\u00f3m k\u1ebft qu\u1ea3 theo document_id.\"\"\"\n",
            "        docs: dict = {}\n",
            "        for r in results:\n",
            "            if r.document_id not in docs:\n",
            "                docs[r.document_id] = {\n",
            "                    \"doc_number\": r.doc_number,\n",
            "                    \"title\": r.title,\n",
            "                    \"legal_type\": r.legal_type,\n",
            "                    \"chunks\": [],\n",
            "                    \"max_score\": 0.0,\n",
            "                    \"articles\": set(),\n",
            "                }\n",
            "            docs[r.document_id][\"chunks\"].append(r)\n",
            "            docs[r.document_id][\"max_score\"] = max(\n",
            "                docs[r.document_id][\"max_score\"], r.score\n",
            "            )\n",
            "            if r.article_hint:\n",
            "                docs[r.document_id][\"articles\"].add(r.article_hint)\n",
            "        for doc in docs.values():\n",
            "            try:\n",
            "                doc[\"articles\"] = sorted(\n",
            "                    doc[\"articles\"],\n",
            "                    key=lambda x: int(re.search(r'\\d+', x).group())\n",
            "                )\n",
            "            except Exception:\n",
            "                doc[\"articles\"] = sorted(doc[\"articles\"])\n",
            "        return docs\n",
            "\n",
            "\n",
            "\n",
            "class QwenGenerator:\n",
            "    def __init__(self, model_name=\"Qwen/Qwen2.5-0.5B-Instruct\"):\n",
            "        self.model_name = model_name\n",
            "        self._tokenizer = None\n",
            "        self._model = None\n",
            "        self._is_vllm = False\n",
            "        \n",
            "    def _load_model(self):\n",
            "        if self._model is not None:\n",
            "            return\n",
            "        \n",
            "        import torch\n",
            "        use_vllm = False\n",
            "        if torch.cuda.is_available():\n",
            "            try:\n",
            "                from vllm import LLM\n",
            "                use_vllm = True\n",
            "            except ImportError:\n",
            "                use_vllm = False\n",
            "                \n",
            "        if use_vllm:\n",
            "            print(f\"[generator] Loading {self.model_name} on GPU with vLLM...\", flush=True)\n",
            "            try:\n",
            "                from vllm import LLM\n",
            "                self._model = LLM(\n",
            "                    model=self.model_name,\n",
            "                    trust_remote_code=True,\n",
            "                    dtype=\"bfloat16\" if torch.cuda.is_bf16_supported() else \"float16\",\n",
            "                    gpu_memory_utilization=0.85,\n",
            "                    tensor_parallel_size=torch.cuda.device_count(),\n",
            "                    enforce_eager=False\n",
            "                )\n",
            "                self._tokenizer = self._model.get_tokenizer()\n",
            "                self._is_vllm = True\n",
            "                print(\"[generator] Model loaded with vLLM successfully.\")\n",
            "                return\n",
            "            except Exception as e:\n",
            "                print(f\"[generator] vLLM load failed: {e}. Falling back to transformers...\", flush=True)\n",
            "                \n",
            "        print(f\"[generator] Loading {self.model_name} on GPU with Transformers...\", flush=True)\n",
            "        self._tokenizer = AutoTokenizer.from_pretrained(self.model_name)\n",
            "        self._model = AutoModelForCausalLM.from_pretrained(\n",
            "            self.model_name,\n",
            "            torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,\n",
            "            device_map=\"auto\"\n",
            "        )\n",
            "        print(\"[generator] Model loaded successfully.\")\n",
            "            \n",
            "    def rewrite_question(self, question: str) -> str:\n",
            "        self._load_model()\n",
            "        system_prompt = (\n",
            "            \"Bạn là một chuyên gia pháp lý. Hãy viết lại câu hỏi sau thành một câu truy vấn tìm kiếm pháp lý ngắn gọn (5-15 từ) \"\n",
            "            \"tập trung vào các từ khóa pháp luật cốt lõi (như hành vi, tên bộ luật, điều khoản hoặc chủ thể liên quan).\\n\"\n",
            "            \"Tuyệt đối không giải thích gì thêm, chỉ trả về câu truy vấn sau khi viết lại.\"\n",
            "        )\n",
            "        prompt = f\"Câu hỏi gốc: \\\"{question}\\\"\\n\\nCâu truy vấn:\"\n",
            "        messages = [\n",
            "            {\"role\": \"system\", \"content\": system_prompt},\n",
            "            {\"role\": \"user\", \"content\": prompt}\n",
            "        ]\n",
            "        formatted_prompt = self._tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
            "        \n",
            "        if getattr(self, '_is_vllm', False):\n",
            "            from vllm import SamplingParams\n",
            "            sampling_params = SamplingParams(max_tokens=50, temperature=0.0)\n",
            "            outputs = self._model.generate([formatted_prompt], sampling_params, use_tqdm=False)\n",
            "            rewritten = outputs[0].outputs[0].text.strip()\n",
            "            return rewritten.replace('\"', '').replace(\"'\", \"\").strip()\n",
            "            \n",
            "        inputs = self._tokenizer([formatted_prompt], return_tensors=\"pt\").to(self._model.device)\n",
            "        \n",
            "        outputs = self._model.generate(\n",
            "            **inputs,\n",
            "            max_new_tokens=50,\n",
            "            do_sample=False,\n",
            "            pad_token_id=self._tokenizer.eos_token_id\n",
            "        )\n",
            "        generated_ids = [\n",
            "            output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, outputs)\n",
            "        ]\n",
            "        rewritten = self._tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()\n",
            "        return rewritten.replace('\"', '').replace(\"'\", \"\").strip()\n",
            "\n",
            "    def generate_answer(self, query: str, context, max_new_tokens: int = 512, warning_msg = None) -> str:\n",
            "        self._load_model()\n",
            "        \n",
            "        if not isinstance(context, str):\n",
            "            # list of RetrievalResult\n",
            "            context_parts = []\n",
            "            for idx, r in enumerate(context, start=1):\n",
            "                doc_name = f\"{r.legal_type} {r.doc_number}\"\n",
            "                article = r.article_hint or \"Toàn bộ\"\n",
            "                body = r.content\n",
            "                if \"Nội dung:\" in body:\n",
            "                    body = body.split(\"Nội dung:\", 1)[1].strip()\n",
            "                part = (\n",
            "                    f\"[Căn cứ {idx}]\\n\"\n",
            "                    f\"Độ liên quan: {r.score:.4f}\\n\"\n",
            "                    f\"Văn bản: {doc_name}\\n\"\n",
            "                    f\"Điều: {article}\\n\"\n",
            "                    f\"Nội dung:\\n{body}\"\n",
            "                )\n",
            "                context_parts.append(part)\n",
            "            context_str = \"\\n\\n=========================================\\n\\n\".join(context_parts)\n",
            "        else:\n",
            "            context_str = context\n",
            "            \n",
            "        system_prompt = (\n",
            "            \"Bạn là một trợ lý pháp lý Việt Nam chuyên nghiệp, chính xác và đáng tin cậy.\\n\\n\"\n",
            "            \"Nhiệm vụ của bạn:\\n\"\n",
            "            \"- Trả lời câu hỏi dựa trên TÀI LIỆU THAM KHẢO CUNG CẤP. Tuyệt đối không tự suy diễn hoặc giả định các nội dung không có trong tài liệu.\\n\"\n",
            "            \"- Hãy viết hoàn toàn bằng tiếng Việt chuẩn mực. Tuyệt đối KHÔNG trộn lẫn tiếng Trung (chữ Hán), tiếng Anh hoặc bất kỳ từ ngữ nước ngoài nào khác.\\n\"\n",
            "            \"- Tuyệt đối KHÔNG sử dụng tên văn bản, điều luật hoặc các từ ngữ trong Ví dụ mẫu (Few-shot) như 'Luật A', 'Nghị định B', 'Nghị định C', 'hành vi X', 'hành vi Y' để trả lời cho câu hỏi thực tế.\\n\"\n",
            "            \"- Tuyệt đối KHÔNG được đánh đồng hoặc suy diễn sai lệch các khái niệm pháp lý khác nhau (ví dụ: việc 'hỗ trợ ngân sách nhà nước' hoặc 'tài trợ' không được diễn giải thành 'ưu đãi về thuế').\\n\"\n",
            "            \"- Cực kỳ cẩn thận với các từ phủ định hoặc hành vi cấm: các cụm từ như 'nghiêm cấm', 'không được', 'xử phạt đối với hành vi' có nghĩa là hành vi đó BỊ CẤM, tuyệt đối không được viết thành 'người sử dụng lao động có trách nhiệm thực hiện' hoặc 'được phép thực hiện'.\\n\"\n",
            "            \"- Nếu tài liệu chứa các số liệu cụ thể như mức tiền phạt (ví dụ: 'từ 20.000.000 đồng đến 25.000.000 đồng'), thời hạn, tỷ lệ phần trăm hoặc các điều kiện hỗ trợ, bạn BẮT BUỘC phải ghi rõ ràng, chính xác các số liệu đó.\\n\"\n",
            "            \"- Không chỉ nêu tên văn bản chung chung. Bạn phải giải thích cụ thể nội dung quyền lợi, nghĩa vụ, ưu đãi hoặc mức phạt được quy định.\\n\"\n",
            "            \"- Nếu có nhiều văn bản cùng điều chỉnh một vấn đề, hãy tổng hợp thông tin một cách mạch lạc. Ưu tiên áp dụng quy định của văn bản có hiệu lực pháp lý cao hơn (ví dụ: Bộ luật/Luật > Nghị quyết > Nghị định > Thông tư).\\n\\n\"\n",
            "            \"Bạn BẮT BUỘC phải trình bày câu trả lời của mình nghiêm ngặt theo cấu trúc 4 phần sau (sử dụng chính xác các tiêu đề này làm tiêu đề dòng):\\n\"\n",
            "            \"1. Trả lời trực tiếp: Trả lời trực tiếp vào câu hỏi, nêu rõ kết luận chính hoặc hành vi và hệ quả.\\n\"\n",
            "            \"2. Phân tích chi tiết: Diễn giải chi tiết nội dung quy định, mức phạt bằng tiền cụ thể, quyền lợi/nghĩa vụ chi tiết được quy định trong các tài liệu tham khảo.\\n\"\n",
            "            \"3. Căn cứ pháp lý: Liệt kê chi tiết các điều khoản, điều luật cụ thể được sử dụng làm căn cứ từ tài liệu tham khảo (Ví dụ: 'Điều A Luật X', 'Điều B Nghị định Y').\\n\"\n",
            "            \"4. Hạn chế của dữ liệu (nếu có): Nêu rõ nếu tài liệu tham khảo thiếu thông tin hoặc không đủ cơ sở để trả lời đầy đủ một khía cạnh nào đó của câu hỏi.\"\n",
            "        )\n",
            "        \n",
            "        user_content = (\n",
            "            f\"TÀI LIỆU THAM KHẢO CUNG CẤP:\\n\"\n",
            "            f\"=========================================\\n\"\n",
            "            f\"{context_str}\\n\"\n",
            "            f\"=========================================\\n\\n\"\n",
            "            f\"{f'LƯU Ý QUAN TRỌNG TỪ HỆ THỐNG: {warning_msg}\\n\\n' if warning_msg else ''}\"\n",
            "            f\"CÂU HỎI: {query}\\n\\n\"\n",
            "            f\"Yêu cầu trả lời: Hãy phân tích kỹ tài liệu tham khảo trên và trả lời câu hỏi tuân thủ đúng cấu trúc 4 phần nêu trên.\\n\"\n",
            "        )\n",
            "        \n",
            "        messages = [\n",
            "            {\"role\": \"system\", \"content\": system_prompt},\n",
            "            # Few-shot example about abstract laws to prevent semantic cross-leakage\n",
            "            {\"role\": \"user\", \"content\": (\n",
            "                \"TÀI LIỆU THAM KHẢO CUNG CẤP:\\n\"\n",
            "                \"=========================================\\n\"\n",
            "                \"Tài liệu [1]: Luật A năm 2020 | Điều 10. Hành vi nghiêm cấm\\n\"\n",
            "                \"Nội dung: Điều 10. Nghiêm cấm tổ chức, cá nhân thực hiện hành vi X dưới mọi hình thức để đảm bảo an toàn.\\n\\n\"\n",
            "                \"Tài liệu [2]: Nghị định B quy định về xử phạt vi phạm hành chính | Điều 15. Xử phạt hành vi X\\n\"\n",
            "                \"Nội dung: Điều 15.\\n\"\n",
            "                \"3. Phạt tiền từ 10.000.000 đồng đến 20.000.000 đồng đối với hành vi vi phạm X.\\n\"\n",
            "                \"10. Biện pháp khắc phục hậu quả:\\n\"\n",
            "                \"b) Buộc khôi phục lại tình trạng ban đầu đối với hành vi quy định tại khoản 3 Điều này trong thời hạn 30 ngày;\\n\\n\"\n",
            "                \"Tài liệu [3]: Nghị định C | Điều 12. Vi phạm quy định về hành vi Y\\n\"\n",
            "                \"Nội dung: Điều 12. Phạt tiền từ 1.000.000 đồng đến 2.000.000 đồng đối với hành vi Y.\\n\"\n",
            "                \"=========================================\\n\\n\"\n",
            "                \"CÂU HỎI: Cá nhân thực hiện hành vi X thì bị phạt bao nhiêu tiền và phải thực hiện biện pháp khắc phục hậu quả gì?\\n\\n\"\n",
            "                \"Yêu cầu trả lời: Hãy phân tích kỹ tài liệu tham khảo trên và trả lời câu hỏi tuân thủ đúng cấu trúc 4 phần nêu trên.\"\n",
            "            )},\n",
            "            {\"role\": \"assistant\", \"content\": (\n",
            "                \"1. Trả lời trực tiếp: Cá nhân thực hiện hành vi X sẽ bị xử phạt tiền từ 10.000.000 đồng đến 20.000.000 đồng và buộc phải thực hiện biện pháp khắc phục hậu quả là khôi phục lại tình trạng ban đầu.\\n\\n\"\n",
            "                \"2. Phân tích chi tiết:\\n\"\n",
            "                \"- Về hành vi vi phạm: Tổ chức, cá nhân bị nghiêm cấm thực hiện hành vi X dưới mọi hình thức.\\n\"\n",
            "                \"- Về mức phạt tiền: Hành vi vi phạm X đối với cá nhân sẽ bị phạt tiền từ 10.000.000 đồng đến 20.000.000 đồng.\\n\"\n",
            "                \"- Về biện pháp khắc phục hậu quả: Người vi phạm buộc phải khôi phục lại tình trạng ban đầu trong thời hạn 30 ngày.\\n\\n\"\n",
            "                \"3. Căn cứ pháp lý:\\n\"\n",
            "                \"- Khoản 1 Điều 10 Luật A năm 2020.\\n\"\n",
            "                \"- Khoản 3 và Điểm b Khoản 10 Điều 15 Nghị định B.\\n\\n\"\n",
            "                \"4. Hạn chế của dữ liệu (nếu có):\\n\"\n",
            "                \"- Tài liệu [3] (Nghị định C) quy định về xử phạt hành vi Y, không liên quan đến hành vi X đang được hỏi nên được bỏ qua khi trả lời.\"\n",
            "            )},\n",
            "            {\"role\": \"user\", \"content\": user_content}\n",
            "        ]\n",
            "        \n",
            "        prompt = self._tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
            "        \n",
            "        if getattr(self, '_is_vllm', False):\n",
            "            from vllm import SamplingParams\n",
            "            sampling_params = SamplingParams(\n",
            "                max_tokens=max_new_tokens,\n",
            "                temperature=0.0,\n",
            "                repetition_penalty=1.05\n",
            "            )\n",
            "            outputs = self._model.generate([prompt], sampling_params, use_tqdm=False)\n",
            "            response = outputs[0].outputs[0].text\n",
            "            return response.strip()\n",
            "            \n",
            "        inputs = self._tokenizer([prompt], return_tensors=\"pt\").to(self._model.device)\n",
            "        \n",
            "        outputs = self._model.generate(\n",
            "            **inputs,\n",
            "            max_new_tokens=max_new_tokens,\n",
            "            do_sample=False,\n",
            "            repetition_penalty=1.05,\n",
            "            pad_token_id=self._tokenizer.eos_token_id\n",
            "        )\n",
            "        generated_ids = [\n",
            "            output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, outputs)\n",
            "        ]\n",
            "        response = self._tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]\n",
            "        return response.strip()\n",
            "\n",
            "def rewrite_question(question: str, generator: QwenGenerator) -> str:\n",
            "    return generator.rewrite_question(question)\n",
            "\n",
            "def has_repetitive_loop(text: str) -> bool:\n",
            "    lines = [line.strip() for line in text.split(\"\\n\") if line.strip()]\n",
            "    for i in range(len(lines) - 2):\n",
            "        if lines[i] == lines[i+1] == lines[i+2]:\n",
            "            print(f\"[validator] Phát hiện lặp dòng liên tiếp: '{lines[i]}'\")\n",
            "            return True\n",
            "            \n",
            "    for line in lines:\n",
            "        words = line.split()\n",
            "        if len(words) > 15:\n",
            "            for size in range(2, 9):\n",
            "                for start in range(len(words) - 3 * size):\n",
            "                    w1 = words[start : start + size]\n",
            "                    w2 = words[start + size : start + 2 * size]\n",
            "                    w3 = words[start + 2 * size : start + 3 * size]\n",
            "                    if w1 == w2 == w3:\n",
            "                        print(f\"[validator] Phát hiện lặp cụm từ vô hạn: {' '.join(w1)}\")\n",
            "                        return True\n",
            "    return False\n",
            "\n",
            "def validate_citations(answer: str, results: List[RetrievalResult]) -> bool:\n",
            "    if has_repetitive_loop(answer):\n",
            "        return False\n",
            "    \n",
            "    answer_articles = set(re.findall(r\"Điều\\s+(\\d+)\", answer, re.IGNORECASE))\n",
            "    if answer_articles:\n",
            "        context_articles = set()\n",
            "        for r in results:\n",
            "            if r.article_hint:\n",
            "                matches = re.findall(r\"Điều\\s+(\\d+)\", r.article_hint, re.IGNORECASE)\n",
            "                context_articles.update(matches)\n",
            "            matches_content = re.findall(r\"Điều\\s+(\\d+)\", r.content, re.IGNORECASE)\n",
            "            context_articles.update(matches_content)\n",
            "            \n",
            "        invalid_articles = answer_articles - context_articles\n",
            "        if invalid_articles:\n",
            "            print(f\"[validator] Phát hiện Hallucination! Các Điều sau không có trong Context: {invalid_articles}\")\n",
            "            return False\n",
            "            \n",
            "    answer_docs = set(re.findall(r\"(\\d+/\\d+)\", answer))\n",
            "    if answer_docs:\n",
            "        context_docs = set()\n",
            "        for r in results:\n",
            "            if r.doc_number:\n",
            "                matches = re.findall(r\"(\\d+/\\d+)\", r.doc_number)\n",
            "                context_docs.update(matches)\n",
            "            matches_content = re.findall(r\"(\\d+/\\d+)\", r.content)\n",
            "            context_docs.update(matches_content)\n",
            "            \n",
            "        invalid_docs = answer_docs - context_docs\n",
            "        if invalid_docs:\n",
            "            print(f\"[validator] Phát hiện Hallucination! Các Văn bản sau không có trong Context: {invalid_docs}\")\n",
            "            return False\n",
            "            \n",
            "    return True\n",
            "\n",
            "def generate_rule_based_answer(results: List[RetrievalResult]) -> str:\n",
            "    if not results:\n",
            "        return \"Không tìm thấy căn cứ pháp lý liên quan để trả lời câu hỏi này.\"\n",
            "    \n",
            "    answer_parts = [\"1. Trả lời trực tiếp: Dưới đây là thông tin trích xuất từ các tài liệu pháp lý được tìm thấy:\"]\n",
            "    citations = []\n",
            "    \n",
            "    for idx, r in enumerate(results[:3], start=1):\n",
            "        ref = f\"{r.legal_type} số {r.doc_number}\"\n",
            "        if r.title:\n",
            "            ref = f\"{r.legal_type} {r.doc_number} ({r.title})\"\n",
            "        if r.article_hint:\n",
            "            ref = f\"{r.article_hint} {ref}\"\n",
            "            \n",
            "        content_snippet = r.content.strip()\n",
            "        if \"Nội dung:\" in content_snippet:\n",
            "            content_snippet = content_snippet.split(\"Nội dung:\", 1)[1].strip()\n",
            "            \n",
            "        if len(content_snippet) > 250:\n",
            "            content_snippet = content_snippet[:247] + \"...\"\n",
            "            \n",
            "        answer_parts.append(f\"- Nguồn {idx}: {content_snippet}\")\n",
            "        citations.append(f\"- {ref}\")\n",
            "        \n",
            "    answer_parts.append(\"2. Phân tích chi tiết:\\nXem chi tiết nội dung các văn bản trên.\")\n",
            "    \n",
            "    if citations:\n",
            "        answer_parts.append(\"3. Căn cứ pháp lý:\\n\" + \"\\n\".join(citations))\n",
            "    else:\n",
            "        answer_parts.append(\"3. Căn cứ pháp lý:\\nKhông rõ.\")\n",
            "        \n",
            "    answer_parts.append(\"4. Hạn chế của dữ liệu (nếu có):\\nKhông có.\")\n",
            "    return \"\\n\\n\".join(answer_parts)\n",
            "\n",
            "def format_structured_context(results: List[RetrievalResult]) -> str:\n",
            "    parts = []\n",
            "    for idx, r in enumerate(results, 1):\n",
            "        doc_name = f\"{r.legal_type} {r.doc_number}\"\n",
            "        article = r.article_hint or \"Toàn bộ\"\n",
            "        \n",
            "        body = r.content\n",
            "        if \"Nội dung:\" in body:\n",
            "            body = body.split(\"Nội dung:\", 1)[1].strip()\n",
            "            \n",
            "        part = (\n",
            "            f\"[Căn cứ {idx}]\\n\"\n",
            "            f\"Độ liên quan: {r.score:.4f}\\n\"\n",
            "            f\"Văn bản: {doc_name}\\n\"\n",
            "            f\"Điều: {article}\\n\"\n",
            "            f\"Nội dung:\\n{body}\"\n",
            "        )\n",
            "        parts.append(part)\n",
            "    return \"\\n\\n=========================================\\n\\n\".join(parts)\n",
            "\n",
            "def build_submission_entry(qid: int, question: str, results: List[RetrievalResult], answer: str = \"\") -> dict:\n",
            "    docs_seen = set()\n",
            "    articles_seen = set()\n",
            "    relevant_docs = []\n",
            "    relevant_articles = []\n",
            "\n",
            "    for r in results:\n",
            "        doc_str = r.format_relevant_doc()\n",
            "        if doc_str not in docs_seen:\n",
            "            docs_seen.add(doc_str)\n",
            "            relevant_docs.append(doc_str)\n",
            "\n",
            "        if r.article_hint:\n",
            "            art_str = r.format_relevant_article()\n",
            "            if art_str not in articles_seen:\n",
            "                articles_seen.add(art_str)\n",
            "                relevant_articles.append(art_str)\n",
            "\n",
            "    return {\n",
            "        \"id\": qid,\n",
            "        \"question\": question,\n",
            "        \"answer\": answer,\n",
            "        \"relevant_docs\": relevant_docs,\n",
            "        \"relevant_articles\": relevant_articles,\n",
            "    }\n",
            "\n",
            "def run_pipeline(input_path, output_path, retriever, generator, use_rerank=True, use_llm=True):\n",
            "    with open(input_path, \"r\", encoding=\"utf-8\") as f:\n",
            "        questions = json.load(f)\n",
            "        \n",
            "    if not isinstance(questions, list):\n",
            "        questions = [questions]\n",
            "        \n",
            "    print(f\"Loaded {len(questions)} questions from {input_path}\")\n",
            "    submission = []\n",
            "    total_time = 0.0\n",
            "    \n",
            "    for idx, q in enumerate(questions, start=1):\n",
            "        qid = q.get(\"id\", idx)\n",
            "        question = q.get(\"question\", \"\")\n",
            "        \n",
            "        t0 = time.time()\n",
            "        try:\n",
            "            # Step 1: Query Rewrite\n",
            "            search_query = question\n",
            "            if use_llm:\n",
            "                try:\n",
            "                    rewritten = rewrite_question(question, generator)\n",
            "                    search_query = f\"{rewritten} {question}\"\n",
            "                    print(f\"\\n[{idx}/{len(questions)}] id={qid} | Original: '{question}' -> Search: '{search_query}'\")\n",
            "                except Exception as re_err:\n",
            "                    print(f\"[rewrite_error] {re_err}\")\n",
            "            \n",
            "            # Step 2 & 3: Retrieval and Rerank\n",
            "            results = retriever.retrieve(search_query, mode=\"hybrid\", top_k=3, rerank=use_rerank)\n",
            "            \n",
            "            # Step 4 & 5: Context Compression and Structured Context\n",
            "            context_str = format_structured_context(results)\n",
            "            \n",
            "            # Step 6: Generator and Citation Validation\n",
            "            answer = \"\"\n",
            "            if use_llm:\n",
            "                answer = generator.generate_answer(question, context_str)\n",
            "                \n",
            "                if not validate_citations(answer, results):\n",
            "                    print(f\"[{qid}] Hallucination detected in first attempt. Regenerating...\")\n",
            "                    context_with_warning = (\n",
            "                        \"CHÚ Ý QUAN TRỌNG: Bạn chỉ được phép sử dụng thông tin và số Điều luật có trong các Căn cứ dưới đây. \"\n",
            "                        \"Tuyệt đối KHÔNG tự bịa ra Điều luật hoặc tên nghị định khác.\\n\\n\"\n",
            "                    ) + context_str\n",
            "                    answer = generator.generate_answer(question, context_with_warning)\n",
            "                    \n",
            "                    if not validate_citations(answer, results):\n",
            "                        print(f\"[{qid}] Hallucination detected in second attempt. Falling back to rule-based answer.\")\n",
            "                        answer = generate_rule_based_answer(results)\n",
            "            else:\n",
            "                answer = generate_rule_based_answer(results)\n",
            "                \n",
            "            elapsed = time.time() - t0\n",
            "            total_time += elapsed\n",
            "            \n",
            "            docs_count = len(results)\n",
            "            has_ans = \"Yes\" if answer else \"No\"\n",
            "            print(f\"  [{idx:3d}/{len(questions)}] Done in {elapsed:.2f}s | {docs_count} docs | Answered: {has_ans}\")\n",
            "            \n",
            "            entry = build_submission_entry(qid, question, results, answer=answer)\n",
            "            submission.append(entry)\n",
            "            \n",
            "        except Exception as e:\n",
            "            elapsed = time.time() - t0\n",
            "            print(f\"  [{idx:3d}/{len(questions)}] Error: {e} ({elapsed:.2f}s)\")\n",
            "            submission.append({\n",
            "                \"id\": qid,\n",
            "                \"question\": question,\n",
            "                \"answer\": \"\",\n",
            "                \"relevant_docs\": [],\n",
            "                \"relevant_articles\": [],\n",
            "            })\n",
            "            \n",
            "    with open(output_path, \"w\", encoding=\"utf-8\") as f:\n",
            "        json.dump(submission, f, ensure_ascii=False, indent=2)\n",
            "        \n",
            "    avg_time = total_time / len(questions) if questions else 0\n",
            "    print(\"-\" * 60)\n",
            "    print(f\"✓ Xong! Đã lưu {len(submission)} câu trả lời vào {output_path} (avg {avg_time:.2f}s/câu)\")\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 🏃‍♂️ Bước 4: Chạy Pipeline RAG chính trên tập câu hỏi"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import json\n",
            "\n",
            "input_path = \"/kaggle/working/R2AIStage1DATA.json\"\n",
            "output_path = \"/kaggle/working/results.json\"\n",
            "\n",
            "# Khởi tạo Retriever\n",
            "retriever = LocalRetriever(top_k=5)\n",
            "\n",
            "# Khởi tạo Generator (sử dụng Qwen-0.5B trên Kaggle)\n",
            "generator = QwenGenerator(model_name=\"Qwen/Qwen2.5-0.5B-Instruct\")\n",
            "\n",
            "# Thực thi pipeline\n",
            "run_pipeline(\n",
            "    input_path=input_path,\n",
            "    output_path=output_path,\n",
            "    retriever=retriever,\n",
            "    generator=generator,\n",
            "    use_rerank=True,\n",
            "    use_llm=True\n",
            ")\n",
            "\n",
            "# Đóng kết nối database\n",
            "retriever.close()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 🗜️ Bước 5: Nén kết quả và chuẩn bị nộp bài"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import zipfile\n",
            "\n",
            "target_json = \"results.json\"\n",
            "zip_name = \"results.zip\"\n",
            "\n",
            "if os.path.exists(target_json):\n",
            "    print(f\"Đang nén file {target_json} thành {zip_name}...\")\n",
            "    with zipfile.ZipFile(zip_name, \"w\", zipfile.ZIP_DEFLATED) as zipf:\n",
            "        zipf.write(target_json, os.path.basename(target_json))\n",
            "    print(\"🎉 Đã nén thành công! Bạn có thể tải file 'results.zip' ở tab output bên phải màn hình để nộp bài.\")\n",
            "else:\n",
            "    print(\"❌ Không tìm thấy file results.json. Vui lòng kiểm tra lại logs ở Bước 4.\")"
        ]
    }
]

# Write notebook structure
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f"Successfully wrote self-contained notebook to {notebook_path}")
